---
title: "About me"
---

I'm a 2nd year PhD student in linguistics at the [University of Southern California](https://dornsife.usc.edu/ling).

I am working in phonetics, phonology, and psycholinguistics, and am specifically interested in how these areas can give us insights on the structural organization of speech. My current research project focuses on prosodic expectations and metrical predictability during speech perception, to determine to what extent listeners use phrase-level phonological processes (e.g. the Rhythm Rule in English) to constrain lexical access. 

Before doing linguistics, I was training to be a professional ballet and contemporary dancer. I've also trained in music, and played the violin for quite a long time. As a result, I am interested in the parallels that can be drawn between language, dance and music, both in speech production and perception. 

---

At USC, I am part of the [USC Phonetics and Phonology group](https://sites.google.com/view/uscphongroup/).

---

I'm originally from France, and completed my MA at [Université Paris-Diderot](https://www.linguist.univ-paris-diderot.fr/) before moving to Los Angeles. In my free time, I enjoy doing yoga and taking strolls in Griffith Park!